FROM golang:1.13.4-alpine3.10
FROM node:13.2.0-alpine3.10
RUN ls -al
COPY . /go/src
RUN ls /go/src -al
CMD ["go", "get", "-u", "google.golang.org/grpc"]
CMD ["go", "get", "-u", "github.com/golang/protobuf/protoc-gen-go"]
WORKDIR /code
CMD ["PROTOC_ZIP=protoc-3.7.1-linux-x86_64.zip"]
CMD ["curl", "-OL", "https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/$PROTOC_ZIP"]
CMD ["sudo", "-i"]
CMD ["sudo", "unzip", "-o", "$PROTOC_ZIP", "-d", "/usr/local", "bin/protoc"]
CMD ["sudo", "unzip", "-o", "$PROTOC_ZIP", "-d", "/usr/local", "'include/*'"]
CMD ["rm", "-f", "$PROTOC_ZIP"]